config:
  name: crud-configmap
  port: 8000
  database: postgresql
  ddl: create
  driver: org.postgresql.Driver
secret:
    name: crud-secret
deployment:
  app:
    name: crud-deployment
    type: NodePort
    image: helloips/crud:1.0
    port: 8000
    replicas: 2
  db:
    name: postresql-deployment
    type: NodePort
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: crud-service
    type: NodePort
    protocol: TCP
    port: 8000
  db:
    name: postresql-service
    type: NodePort
    dbname: db
    host: "postresql-service"
    port: 5432
    sport: "5432"
ingress:
  name: crud-ingress
  host: arch.homework