{
 "title": "OTUS Dashboard by Ivanov Pavel",
 "description": "OTUS HW",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API. Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/metrics\"}[1m])) by (uri)",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Ingress. Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[1m])) by (container)"
    }
   ]
  },
  {
   "title": "API. Response time of 50%, 95%, 99%, max of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{uri=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{uri=\"/metrics\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Ingress. Response time of 50%, 95%, 99%, max of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])*1000))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])*1000))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])*1000))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])*1000))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "API. Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(delta(http_server_requests_seconds_count{status=\"500\"}[1m])) by (uri)"
    }
   ]
  },
  {
   "title": "Ingress. Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(delta(http_server_requests_seconds_count{status=\"500\"}[1m])) by (uri)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(container_cpu_usage_seconds_total{pod=~\"metrics-deploy.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(container_memory_usage_bytes{pod=~\"metrics-deploy.*\"}[20m])) by (pod)"
    }
   ]
  },
  {
   "title": "DB Connection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hikaricp_connections" }
   ]
  }
 ]
}