apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  type: NodePort
  selector:
    app: billing-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: billing-db-service
spec:
  type: NodePort
  selector:
    app: billing-db-deployment
  ports:
    - port: 5432
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-deployment
  template:
    metadata:
      labels:
        app: billing-deployment
    spec:
      containers:
        - name: billing
          image: helloips/billing:1.0
          ports:
            - name: web
              containerPort: 8000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: SERVER_PORT
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: SPRING_JPA_DATABASE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: CAMUNDA_REST_API_URI
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: CAMUNDA_REST_API_URI
            - name: CAMUNDA_CLIENT_LOCK_DURATION
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: CAMUNDA_CLIENT_LOCK_DURATION
            - name: CAMUNDA_CLIENT_LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: CAMUNDA_CLIENT_LOGGING_LEVEL
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db-deployment
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: billing-db-deployment
  template:
    metadata:
      labels:
        app: billing-db-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secret
type: Opaque
data:
  DATABASE_USERNAME: YWRtaW4=
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_NAME: ZGI=
  SPRING_DATASOURCE_URL: "amRiYzpwb3N0Z3Jlc3FsOi8vYmlsbGluZy1kYi1zZXJ2aWNlOjU0MzIvZGI="
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-configmap
data:
  SERVER_PORT: "8000"
  SPRING_JPA_DATABASE: "postgresql"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  CAMUNDA_REST_API_URI: "http://orchestrator-service:8000/rest"
  CAMUNDA_CLIENT_LOCK_DURATION: "1000"
  CAMUNDA_CLIENT_LOGGING_LEVEL: "DEBUG"