##################################################################################################
# Health gateway
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: healthvs-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: healthvs
spec:
  hosts:
  - "*"
  gateways:
  - healthvs-gateway
  http:
  - match:
    - uri:
        exact: /health
    route:
    - destination:
        host: health
        port: 
          number: 8012
        subset: v1
      weight: 50
    - destination:
        host: health
        port:
          number: 8012
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: health
spec:
  host: health
  subsets:
  - name: v1
    labels:
      version: "v1"
  - name: v2
    labels:
      version: "v2"
---          